name: app_client
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # System Icons
  cupertino_icons: ^1.0.8

  # State Management
  provider: ^6.0.5

  # HTTP & API
  http: ^1.2.1
  dio: ^5.3.2

  # Local Storage
  shared_preferences: ^2.2.2

  # Location & Maps
  geolocator: ^10.1.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0

  # UI & Animations
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0

  # Utilities
  intl: ^0.18.1
  uuid: ^4.1.0

  # Push Notifications
  firebase_messaging: ^14.7.6

  # Image handling
  image_picker: ^1.0.4
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
